# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(746, 485)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.camera_map = QtWidgets.QHBoxLayout()
        self.camera_map.setObjectName("camera_map")
        self.camera = QtWidgets.QWidget(self.centralwidget)
        self.camera.setObjectName("camera")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.camera)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.screenCamera = QtWidgets.QGraphicsView(self.camera)
        self.screenCamera.setObjectName("screenCamera")
        self.verticalLayout_4.addWidget(self.screenCamera)
        self.camera_map.addWidget(self.camera)
        self.verticalLayout.addLayout(self.camera_map)
        self.connection = QtWidgets.QFrame(self.centralwidget)
        self.connection.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.connection.setFrameShadow(QtWidgets.QFrame.Raised)
        self.connection.setObjectName("connection")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.connection)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btnCamera = QtWidgets.QPushButton(self.connection)
        self.btnCamera.setObjectName("btnCamera")
        self.horizontalLayout_7.addWidget(self.btnCamera)
        self.btnConnection = QtWidgets.QPushButton(self.connection)
        self.btnConnection.setObjectName("btnConnection")
        self.horizontalLayout_7.addWidget(self.btnConnection)
        self.verticalLayout.addWidget(self.connection)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 746, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dock_command = QtWidgets.QDockWidget(MainWindow)
        self.dock_command.setObjectName("dock_command")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.command = QtWidgets.QHBoxLayout()
        self.command.setObjectName("command")
        self.camera_command = QtWidgets.QWidget(self.dockWidgetContents)
        self.camera_command.setObjectName("camera_command")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.camera_command)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnTakePicture = QtWidgets.QPushButton(self.camera_command)
        self.btnTakePicture.setObjectName("btnTakePicture")
        self.horizontalLayout_5.addWidget(self.btnTakePicture)
        self.btnVideo = QtWidgets.QPushButton(self.camera_command)
        self.btnVideo.setObjectName("btnVideo")
        self.horizontalLayout_5.addWidget(self.btnVideo)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnViewPhoto = QtWidgets.QPushButton(self.camera_command)
        self.btnViewPhoto.setObjectName("btnViewPhoto")
        self.horizontalLayout_6.addWidget(self.btnViewPhoto)
        self.btnViewVideo = QtWidgets.QPushButton(self.camera_command)
        self.btnViewVideo.setObjectName("btnViewVideo")
        self.horizontalLayout_6.addWidget(self.btnViewVideo)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.command.addWidget(self.camera_command)
        self.mouvement = QtWidgets.QWidget(self.dockWidgetContents)
        self.mouvement.setObjectName("mouvement")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mouvement)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnForward = QtWidgets.QToolButton(self.mouvement)
        self.btnForward.setObjectName("btnForward")
        self.horizontalLayout_2.addWidget(self.btnForward)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnLeft = QtWidgets.QToolButton(self.mouvement)
        self.btnLeft.setObjectName("btnLeft")
        self.horizontalLayout.addWidget(self.btnLeft)
        self.btnStop = QtWidgets.QToolButton(self.mouvement)
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout.addWidget(self.btnStop)
        self.btnRight = QtWidgets.QToolButton(self.mouvement)
        self.btnRight.setObjectName("btnRight")
        self.horizontalLayout.addWidget(self.btnRight)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnBackward = QtWidgets.QToolButton(self.mouvement)
        self.btnBackward.setObjectName("btnBackward")
        self.horizontalLayout_3.addWidget(self.btnBackward)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.command.addWidget(self.mouvement)
        self.verticalLayout_5.addLayout(self.command)
        self.dock_command.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dock_command)
        self.dock_map = QtWidgets.QDockWidget(MainWindow)
        self.dock_map.setObjectName("dock_map")
        self.dock_container_map_2 = QtWidgets.QWidget()
        self.dock_container_map_2.setObjectName("dock_container_map_2")
        self.dock_map.setWidget(self.dock_container_map_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dock_map)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnCamera.setText(_translate("MainWindow", "activate/desactivate camera"))
        self.btnConnection.setText(_translate("MainWindow", "Connect to pi"))
        self.btnTakePicture.setText(_translate("MainWindow", "Take Photo"))
        self.btnVideo.setText(_translate("MainWindow", "Start Video"))
        self.btnViewPhoto.setText(_translate("MainWindow", "Show Photo"))
        self.btnViewVideo.setText(_translate("MainWindow", "Show Video"))
        self.btnForward.setText(_translate("MainWindow", "forward"))
        self.btnLeft.setText(_translate("MainWindow", "left"))
        self.btnStop.setText(_translate("MainWindow", "stop"))
        self.btnRight.setText(_translate("MainWindow", "rigth"))
        self.btnBackward.setText(_translate("MainWindow", "backward"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

