# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(963, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.camera = QtWidgets.QWidget(self.centralwidget)
        self.camera.setObjectName("camera")
        self.lblCamera = QtWidgets.QLabel(self.camera)
        self.lblCamera.setGeometry(QtCore.QRect(420, 110, 55, 16))
        self.lblCamera.setObjectName("lblCamera")
        self.verticalLayout.addWidget(self.camera)
        self.command = QtWidgets.QHBoxLayout()
        self.command.setObjectName("command")
        self.camera_command = QtWidgets.QWidget(self.centralwidget)
        self.camera_command.setObjectName("camera_command")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.camera_command)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnTakePicture = QtWidgets.QPushButton(self.camera_command)
        self.btnTakePicture.setObjectName("btnTakePicture")
        self.horizontalLayout_5.addWidget(self.btnTakePicture)
        self.btnVideo = QtWidgets.QPushButton(self.camera_command)
        self.btnVideo.setObjectName("btnVideo")
        self.horizontalLayout_5.addWidget(self.btnVideo)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnViewPhoto = QtWidgets.QPushButton(self.camera_command)
        self.btnViewPhoto.setObjectName("btnViewPhoto")
        self.horizontalLayout_6.addWidget(self.btnViewPhoto)
        self.btnViewVideo = QtWidgets.QPushButton(self.camera_command)
        self.btnViewVideo.setObjectName("btnViewVideo")
        self.horizontalLayout_6.addWidget(self.btnViewVideo)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.command.addWidget(self.camera_command)
        self.mouvement = QtWidgets.QWidget(self.centralwidget)
        self.mouvement.setObjectName("mouvement")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mouvement)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnForward = QtWidgets.QToolButton(self.mouvement)
        self.btnForward.setObjectName("btnForward")
        self.horizontalLayout_2.addWidget(self.btnForward)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnLeft = QtWidgets.QToolButton(self.mouvement)
        self.btnLeft.setObjectName("btnLeft")
        self.horizontalLayout.addWidget(self.btnLeft)
        self.btnStop = QtWidgets.QToolButton(self.mouvement)
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout.addWidget(self.btnStop)
        self.btnRight = QtWidgets.QToolButton(self.mouvement)
        self.btnRight.setObjectName("btnRight")
        self.horizontalLayout.addWidget(self.btnRight)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnBackward = QtWidgets.QToolButton(self.mouvement)
        self.btnBackward.setObjectName("btnBackward")
        self.horizontalLayout_3.addWidget(self.btnBackward)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.command.addWidget(self.mouvement)
        self.verticalLayout.addLayout(self.command)
        self.connection = QtWidgets.QFrame(self.centralwidget)
        self.connection.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.connection.setFrameShadow(QtWidgets.QFrame.Raised)
        self.connection.setObjectName("connection")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.connection)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btnConnection = QtWidgets.QPushButton(self.connection)
        self.btnConnection.setObjectName("btnConnection")
        self.horizontalLayout_7.addWidget(self.btnConnection)
        self.verticalLayout.addWidget(self.connection)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 963, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblCamera.setText(_translate("MainWindow", "TextLabel"))
        self.btnTakePicture.setText(_translate("MainWindow", "Take Photo"))
        self.btnVideo.setText(_translate("MainWindow", "Start Video"))
        self.btnViewPhoto.setText(_translate("MainWindow", "Show Photo"))
        self.btnViewVideo.setText(_translate("MainWindow", "Show Video"))
        self.btnForward.setText(_translate("MainWindow", "forward"))
        self.btnLeft.setText(_translate("MainWindow", "left"))
        self.btnStop.setText(_translate("MainWindow", "stop"))
        self.btnRight.setText(_translate("MainWindow", "rigth"))
        self.btnBackward.setText(_translate("MainWindow", "backward"))
        self.btnConnection.setText(_translate("MainWindow", "Connect "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

